export const ADD_TO_CART = 'ADD_TO_CART';
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_ITEM_QTY = 'INCREMENT_ITEM_QTY';
export const DECREMENT_ITEM_QTY = 'DECREMENT_ITEM_QTY';
export const EMPTY_CART = 'EMPTY_CART';
